package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var versionPattern = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$`)

func main() {
	// When run via go generate, CWD is the package directory (internal/buildinfo/).
	// VERSION is at the repo root: ../../VERSION relative to CWD.
	versionFile := filepath.Join("..", "..", "VERSION")
	version, err := readVersion(versionFile)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	content := fmt.Sprintf(`package buildinfo

// Code generated by tools/buildinfo-gen; DO NOT EDIT.

const Version = %q
`, version)
	if err := os.WriteFile("buildinfo.go", []byte(content), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func readVersion(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	version := strings.TrimSpace(string(data))
	if version == "" {
		return "", fmt.Errorf("VERSION is empty")
	}
	if !versionPattern.MatchString(version) {
		return "", fmt.Errorf("VERSION %q must be semver without leading v", version)
	}
	return version, nil
}
